import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators, FormControl } from '@angular/forms';

import { ListView, isIOS } from '@nativescript/core';
import { Router } from '@angular/router';
// require('nativescript-websockets');


@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.scss']
})
export class AutoGeneratedComponent implements OnInit {

  private listView: ListView;
  public items = new Array<any>(
    { id: 1, name: "Ter Stegen", role: "Goalkeeper" },
    { id: 3, name: "Piqué", role: "Defender" },
    { id: 4, name: "I. Rakitic", role: "Midfielder" },
    { id: 5, name: "Sergio", role: "Midfielder" },
    { id: 6, name: "Denis Suárez", role: "Midfielder" },
    { id: 7, name: "Arda", role: "Midfielder" },
    { id: 8, name: "A. Iniesta", role: "Midfielder" },
    { id: 9, name: "Suárez", role: "Forward" },
    { id: 10, name: "Messi", role: "Forward" },
    { id: 11, name: "Neymar", role: "Forward" },
    { id: 12, name: "Rafinha", role: "Midfielder" },
    { id: 13, name: "Cillessen", role: "Goalkeeper" },
    { id: 14, name: "Mascherano", role: "Defender" },
    { id: 17, name: "Paco Alcácer", role: "Forward" },
    { id: 18, name: "Jordi Alba", role: "Defender" },
    { id: 19, name: "Digne", role: "Defender" },
    { id: 20, name: "Sergi Roberto", role: "Midfielder" },
    { id: 21, name: "André Gomes", role: "Midfielder" },
    { id: 22, name: "Aleix Vidal", role: "Midfielder" },
    { id: 23, name: "Umtiti", role: "Defender" },
    { id: 24, name: "Mathieu", role: "Defender" },
    { id: 25, name: "Masip", role: "Goalkeeper" }
);


public items1 = new Array<any>(
  { id: 26, name: "Ter Stegen", role: "Goalkeeper" },
  { id: 27, name: "Piqué", role: "Defender" },
  { id: 28, name: "I. Rakitic", role: "Midfielder" },
  { id: 29, name: "Sergio", role: "Midfielder" },
  { id: 30, name: "Denis Suárez", role: "Midfielder" },
  { id: 31, name: "Arda", role: "Midfielder" },
  { id: 32, name: "A. Iniesta", role: "Midfielder" },
);
  public formLogin:FormGroup;
  constructor(
    private route:  Router,
    private formBuilder: FormBuilder,
  ) { }

  ngOnInit() {

   
    this.formLogin = this.formBuilder.group({
      emailAddress:new FormControl('', [Validators.required]),
    });
		}

  public click(){
    console.log(this.formLogin.value.emailAddress);
    this.route.navigate(['/item']);
  }

}
